plugins {
  id 'cairo.java-library'
}

dependencies {
  api(project(':auth:core'))
  api(project(':auth:domain:core'))
  api('jakarta.validation:jakarta.validation-api')
  compileOnly('org.hibernate.validator:hibernate-validator')
  compileOnly(project(':framework:rabbitmq'))
  compileOnly('org.springframework.data:spring-data-mongodb')
}
