FROM nginx:stable
COPY . /etc/nginx/
#RUN apt install gettext -y && apt autoremove -y;

#ENTRYPOINT /bin/bash -c "envsubst '\$minio \$domain' < /etc/nginx/template.d/minio.conf > /etc/nginx/conf.d/minio.conf && exec nginx -g 'daemon off;'"
