server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    server_name _;

    # security
    include     nginxconfig.io/security.conf;

    # logging
    access_log  /var/log/nginx/frontend.access.log;
    error_log   /var/log/nginx/frontend.error.log warn;
    proxy_intercept_errors on;

    proxy_set_header Cookie "";

    proxy_hide_header Vary;
    proxy_hide_header X-Content-Type-Options;
    proxy_hide_header X-Xss-Protection;
    proxy_hide_header Access-Control-Allow-Credentials;
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Content-Security-Policy;
    proxy_hide_header Server;
    proxy_hide_header Strict-Transport-Security;

    proxy_hide_header X-Amz-Bucket-Region;
    proxy_hide_header X-Amz-Replication-Status;
    proxy_hide_header X-Amz-Request-Id;
    proxy_hide_header X-Amz-Version-Id;

    set $proxy_pass "http://baidu.com";


    if ($http_proxy_pass != "") {
        set $proxy_pass $http_proxy_pass;
    }

    # reverse proxy
    location  = /  {
        proxy_pass $proxy_pass/index.html?$args;
        error_page 404 @index2;
    }

    # reverse proxy
    location /  {
        proxy_pass $proxy_pass$uri?$args;
        error_page 404 @index1;
    }

    location @index1 {
        proxy_pass $proxy_pass/index.html?$args;
        error_page 404 @index2;
    }

    location @index2 {
        proxy_pass $proxy_pass/index.htm?$args;
        error_page 404 @error_default;
    }

    location @error_default {
        proxy_pass $proxy_pass$uri?$args;
    }

    # additional config
    include nginxconfig.io/general.conf;
}
